### ISSUE TITLE
Snow park is missing

### ISSUE THREAD

**Issue by YestinJarrett** [kuroppoi/qpang-archive#2]
Snow park is **missing**.

For reference, see:
[https://www.youtube.com/watch?v=CALJvNmWAt8&ab_channel=Dennis](https://www.youtube.com/watch?v=CALJvNmWAt8&ab_channel=Dennis)

**Comment by kuroppoi** [comment]
What a shame :(

**Comment by YestinJarrett** [comment]
Mark as resolved

**Comment by YestinJarrett** [comment]
![bg-login](https://user-images.githubusercontent.com/29265503/144397924-f278c241-900e-48f6-89d1-9263d810f233.png)
